name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3.12-fpm-bullseye'
        
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      env:
        DB_CONNECTION: mysql
        DB_HOST: ${{secrets.SISTEMAELLOS_DB_HOST}}
        DB_PORT: 3306
        DB_DATABASE: ${{secrets.SISTEMAELLOS_DB_DATABASE}}
        DB_USERNAME: ${{secrets.SISTEMAELLOS_DB_USERNAME}}
        DB_PASSWORD: ${{secrets.SISTEMAELLOS_DB_PASSWORD}}
        AWS_ACCESS_KEY_ID: 8OOKzQjwB7oDnwRLTfUB
        AWS_SECRET_ACCESS_KEY: P0p1E5NwvptNmr8ytQN4Zf4FYcoF9W20vQItCu2j
        AWS_BUCKET: files-ellos-filament
        AWS_ENDPOINT: https://s3.siellos.online
        APP_ENV: production
        APP_DEBUG: true
        APP_URL: https://ellosadmin.com
        APP_LOCALE: pt_BR
        APP_FALLBACK_LOCALE: pt_BR
        APP_FAKER_LOCALE: pt_BR

    - name: Directory Permissions
      run: mkdir -p storage/framework/{sessions,views,cache} && chmod -R 777 storage bootstrap/cache
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate key
      run: php artisan key:generate

    - name: "Copiar os arquivos para VPS"
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{secrets.SSH_HOST_SERVER}}
        username: ${{secrets.SSH_USER}}
        password: ${{secrets.SSH_PASSWORD}}
        source: "."
        target: "/var/www/ellosadmin"
        strip_components: 1
